ARG SERVICE_NAME
ARG SERVICE_DIR

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copy and restore the service project
COPY ${SERVICE_DIR}/*.csproj ${SERVICE_NAME}/
RUN dotnet restore ${SERVICE_NAME}/*.csproj

# Copy and build the service
COPY ${SERVICE_DIR}/. ${SERVICE_NAME}/
RUN dotnet publish ${SERVICE_NAME}/*.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "service.dll"]