name: Main Pipeline POC

on:
  pull_request:
    branches:
      - main
    paths:
      - "backend/Services/**"

jobs:
  setup:
    name: Setup pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Git Setup
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESSTOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}

      - name: Rebase from main branch
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"

      - name: Calculate new version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true

      - name: Display version
        run: echo ${{ steps.gitversion.outputs.semVer }}

  detect-changes:
    name: Detect changes
    needs: setup
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-changed-services.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          list-files: json
          filters: |
            services:
              - 'backend/Services/**'

      - name: Set changed services
        id: set-changed-services
        run: |
          changed_files='${{ steps.filter.outputs.services_files }}'

          if [ -n "$changed_files" ] && [ "$changed_files" != "null" ]; then
            # Extract unique service names (handling spaces)
            changed_services=$(echo "$changed_files" | jq -r '.[] | split("/")[2]' | sort -u | jq -R -s -c 'split("\n")[:-1]')
          fi
          echo "Changed services: $changed_services"
          echo "::set-output name=services::$changed_services"

  pr-submit-label:
    name: Build container images
    if: ${{ contains(github.event.pull_request.labels.*.name, 'submit') && needs.detect-changes.outputs.services != '[]' }}
    needs: detect-changes
    uses: ./.github/workflows/container_build_pipeline_poc.yml
    with:
      services: ${{ needs.detect-changes.outputs.services }}

  pr-deploy-label:
    name: Deploy single service
    if: ${{ contains(github.event.pull_request.labels.*.name, 'deploy') }}
    needs: detect-changes
    uses: ./.github/workflows/single_build_deploy_pipeline_poc.yml
    with:
      services: ${{ needs.detect-changes.outputs.services }}
