name: Single Container Build and Deploy Pipeline POC

on:
  workflow_call:
    inputs:
      services:
        required: true
        type: string

jobs:
  single-build-deploy:
    name: Single container build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Single build
        run: echo "Single container build..."

      - name: Single deploy
        run: echo "Single container deploy..."
